//
//  PublicPunchLinePaths.swift
//  Punch-Line
//
//  Created by Jeffrey Eugene Hoch on 7/11/20.
//  Copyright © 2020 Bozo Design Labs. All rights reserved.
//

import Foundation

struct PublicPunchLineNames {

    struct MajorRegions {

        static let regionNamesForNewCloudInstance = [usAndCanada]

        static let usAndCanada = "US And Canada"
    }

    struct MidSizedRegions {

        static let regionNamesForNewCloudInstance = [newYork]

        //Canada
        static let alberta = "Alberta"
        static let britishColumbia = "British Columbia"
        static let manitoba = "Manitoba"
        static let newBrunswick = "New Brunswick"
        static let newFoundlandAndLabrador = "NewFoundland And Labrador"
        static let novaScotia = "Nova Scotia"
        static let ontario = "Ontario"
        static let princeEdwardIsland = "Prince Edward Island"
        static let quebec = "Quebec"
        static let saskatchewan = "Saskatchewan"

        //United States
        static let alabama = "Alabama"
        static let alaska = "Alaska"
        static let arizona = "Arizona"
        static let arkansas = "Arkansas"
        static let california = "California"
        static let colorado = "Colorado"
        static let connecticut = "Connecticut"
        static let delaware = "Delaware"
        static let florida = "Florida"
        static let georgia = "Georgia"
        static let hawaii = "Hawaii"
        static let idaho = "Idaho"
        static let illinois = "Illinois"
        static let indiana = "Indiana"
        static let iowa = "Iowa"
        static let kansas = "Kansas"
        static let kentucky = "Kentucky"
        static let louisiana = "Louisiana"
        static let maine = "Maine"
        static let maryland = "Maryland"
        static let massachusetts = "Massachusetts"
        static let michigan = "Michigan"
        static let minnesota = "Minnesota"
        static let mississippi = "Mississippi"
        static let missouri = "Missouri"
        static let montana = "Montana"
        static let nebraska = "Nebraska"
        static let nevada = "Nevada"
        static let newHampsire = "New Hampshire"
        static let newJersey = "New Jersey"
        static let newMexico = "New Mexico"
        static let newYork = "NY"
        static let northCarolina = "North Carolina"
        static let northDakota = "North Dakota"
        static let ohio = "Ohio"
        static let oklahoma = "Oklahoma"
        static let oregon = "Oregon"
        static let pennsylvania = "Pennsylvania"
        static let rhodeIsland = "Rhode Island"
        static let southCarolina = "South Carolina"
        static let southDakota = "SouthDakota"
        static let tennessee = "Tennessee"
        static let texas = "Texas"
        static let utah = "Utah"
        static let vermont = "Vermont"
        static let virginia = "Virginia"
        static let washington = "Washington"
        static let westVirginia = "West Virginia"
        static let wisconsin = "Wisconsin"
        static let wyoming = "Wyoming"
    }

    struct LocalRegions {

        static let regionNamesForNewCloudInstance = [newYork]

        //Canada
        static let toronto = "Toronto"
        static let montreal = "Montreal"
        static let calgary = "Calgary"
        static let ottawa = "Ottawa"
        static let edmonton = "Edmonton"
        static let mississauga = "Mississauga"
        static let winnipeg = "Winnipeg"
        static let vancouver = "Vancouver"
        static let brampton = "Brampton"
        static let hamilton = "Hamilton"
        static let quebecCity = "Quebec City"
        static let surrey = "Surrey"
        static let laval = "Laval"
        static let halifax = "Halifax"
        static let london = "London"
        static let markham = "Markham"
        static let vaughan = "Vaughan"
        static let gatineau = "Gatineau"
        static let saskatoon = "Saskatoon"
        static let longueuil = "Longueuil"

        //United States
        static let newYork = "New York"
        static let losAngeles = "Los Angeles"
        static let chicago = "Chicago"
        static let houston = "Houston"
        static let phoenix = "Phoenix"
        static let philadelphia = "Philadelphia"
        static let sanAntonio = "San Antonio"
        static let sanDiego = "San Diego"
        static let dallas = "Dallas"
        static let sanJose = "San Jose"
        static let austin = "Austin"
        static let jacksonville = "Jacksonville"
        static let fortWorth = "Fort Worth"
        static let columbusOhio = "Columbus, OH"
        static let charlotte = "Charlotte"
        static let sanFrancisco = "San Francisco"
        static let indianapolis = "Indianapolis"
        static let seattle = "Seattle"
        static let denver = "Denver"
        static let washingtonDC = "Washington, D.C."
        static let boston = "Boston"
        static let elPaso = "El Paso"
        static let nashville = "Nashville"
        static let detroit = "Detroit"
        static let oklahomaCity = "Oklahoma City"
        static let portland = "Portland"
        static let lasVegas = "Las Vegas"
        static let memphis = "Memphis"
        static let louisville = "Louisville"
        static let baltimore = "Baltimore"
        static let milwaukee = "Milwaukee"
        static let albuquerque = "Albuquerque"
        static let tucson = "Tucson"
        static let fresno = "Fresno"
        static let mesa = "Mesa"
        static let sacramento = "Sacramento"
        static let atlanta = "Atlanta"
        static let kansasCity = "Kansas City"
        static let coloradoSprings = "Colorado Springs"
        static let omaha = "Omaha"
        static let raleigh = "Raleigh"
        static let miami = "Miami"
        static let longBeach = "Long Beach"
        static let virginiaBeach = "Virginia Beach"
        static let oakland = "Oakland"
        static let minneapolis = "Minneapolis"
        static let tulsa = "Tulsa"
        static let tampa = "Tampa"
        static let arlington = "Arlington"
        static let newOrleans = "New Orleans"
        static let wichita = "Wichita"
        static let bakersfield = "Bakersfield"
        static let cleveland = "Cleveland"
        static let auroraColorado = "Aurora, CO"
        static let anaheim = "Anaheim"
        static let honolulu = "Honolulu"
        static let santaAna = "Santa Ana"
        static let riverside = "Riverside"
        static let corpusChristi = "Corpus Christi"
        static let lexington = "Lexington"
        static let henderson = "Henderson"
        static let stockton = "Stockton"
        static let saintPaul = "Saint Paul"
        static let cincinnati = "Cincinnati"
        static let stLouis = "St. Louis"
        static let pittsburgh = "Pittsburgh"
        static let greensboro = "Greensboro"
        static let lincoln = "Lincoln"
        static let anchorage = "Anchorage"
        static let plano = "Plano"
        static let orlando = "Orlando"
        static let irvine = "Irvine"
        static let newark = "Newark"
        static let durham = "Durham"
        static let chulaVista = "Chula Vista"
        static let toledo = "Toledo"
        static let fortWayne = "Fort Wayne"
        static let stPetersburg = "St. Petersburg"
        static let laredo = "Laredo"
        static let jerseyCity = "Jersey City"
        static let chandler = "Chandler"
        static let madison = "Madison"
        static let lubbock = "Lubbock"
        static let scottsdale = "Scottsdale"
        static let reno = "Reno"
        static let buffalo = "Buffalo"
        static let gilbert = "Gilbert"
        static let glendaleArizona = "Glendale, AZ"
        static let northLasVegas = "North Las Vegas"
        static let winstonSalem = "Winston-Salem"
        static let chesapeake = "Chesapeake"
        static let norfolk = "Norfolk"
        static let fremont = "Fremont"
        static let garland = "Garland"
        static let irving = "Irving"
        static let hialeah = "Hialeah"
        static let richmond = "Richmond"
        static let boise = "Boise"
        static let spokane = "Spokane"
        static let batonRouge = "Baton Rouge"
        static let tacoma = "Tacoma"
        static let sanBernardino = "San Bernardino"
        static let modesto = "Modesto"
        static let fontana = "Fontana"
        static let desMoines = "Des Moines"
        static let morenoValley = "Moreno Valley"
        static let santaClarita = "Santa Clarita"
        static let fayetteville = "Fayetteville"
        static let birmingham = "Birmingham"
        static let oxnard = "Oxnard"
        static let rochester = "Rochester"
        static let portStLucie = "Port St. Lucie"
        static let grandRapids = "Grand Rapids"
        static let huntsVille = "Huntsville"
        static let saltLakeCity = "Salt Lake City"
        static let frisco = "Frisco"
        static let yonkers = "Yonkers"
        static let amarillo = "Amarillo"
        static let glendaleCalifornia = "Glendale, CA"
        static let huntingtonBeach = "Huntington Beach"
        static let mcKinney = "McKinney"
        static let montgomery = "Montgomery"
        static let augusta = "Augusta"
        static let auroraIllinois = "Aurora, IL"
        static let akron = "Akron"
        static let littleRock = "Little Rock"
        static let tempe = "Tempe"
        static let columbusGeorgia = "Columbus, GA"
        static let overlandPark = "Overland Park"
        static let grandPrairie = "Grand Prairie"
        static let tallahassee = "Tallahassee"
        static let capeCoral = "Cape Coral"
        static let mobile = "Mobile"
        static let knoxville = "Knoxville"
        static let shreveport = "Shreveport"
        static let worcester = "Worcester"
        static let ontario = "Ontario"
        static let vancouverWashington = "Vancouver, WA"
        static let siouxFalls = "Sioux Falls"
        static let chattanooga = "Chattanooga"
        static let brownsville = "Brownsville"
        static let fortLauderdale = "Fort Lauderdale"
        static let providence = "Providence"
        static let newportNews = "Newport News"
        static let ranchoCucamonga = "Rancho Cucamonga"
        static let santaRosa = "Santa Rosa"
        static let peoria = "Peoria"
        static let oceanside = "Oceanside"
        static let elkGrove = "Elk Grove"
        static let salem = "Salem"
    }

}
